name: Build axel
on: [push, pull_request]
jobs:
  build_axel:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
        
    - name: Set up msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          gcc
          make
          gettext-devel
          autotools
          autoconf-archive
          libtool
          pkg-config
          openssl-devel
          
    - name: Setup txt2man
      shell: msys2 {0}
      run: |
        wget https://github.com/mvertes/txt2man/archive/refs/tags/txt2man-1.7.1.tar.gz
        tar -zxvf txt2man-1.7.1.tar.gz
        cd txt2man-txt2man-1.7.1
        make && make install
               
    - name: Build axel
      shell: msys2 {0}
      run: |
        autoreconf -ifv
        ./configure  LIBS=-lintl --disable-nls --disable-Werror
        make
 
    - name: Copy Files
      run: |
        cd C:\msys64\usr\bin
        cp msys-2.0.dll, msys-ssl-3.dll, msys-crypto-3.dll, msys-z.dll ${{ github.workspace }}\
        cp ${{ github.workspace }}\**\*.exe ${{ github.workspace }}\
        
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: axel
        path: |
          ${{ github.workspace }}\*.exe
          ${{ github.workspace }}\*.dll
          
    - name: Package Release
      run: 7z a axel.7z -r ${{ github.workspace }}\*.exe ${{ github.workspace }}\*.dll
      
    - name: Release
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v0.1.15
      with:
        draft: false
        prerelease: false
        files: axel.7z